### ISSUE TITLE
(V2) Contributor Console Individual - UI Issues

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla-contributor-console#14]
## Background
1. Launch http://localhost:4200/individual-dashboard/47f742ee-d925-43d2-b1e6-2693b000fca9/f3d11ce1-4533-4844-b6e6-a56584f4672
Observed below issues
**_Issue1 - Font Color is not as expected_**
For SIGN CLA text color should be #E0E0E0 but in UI it is #fff
![image](https://user-images.githubusercontent.com/60865903/82538245-171efe80-9b69-11ea-84c4-1a6a77f0a167.png)

![image](https://user-images.githubusercontent.com/60865903/82538308-2f8f1900-9b69-11ea-845c-7685a465bb4f.png)

**_Issue2: Backgroud color changes to white when height window is minimized in Preparing CLA UI_**
![image](https://user-images.githubusercontent.com/60865903/82539786-a2998f00-9b6b-11ea-9256-70f8ab81d0fc.png)

2.  http://localhost:4200/individual-dashboard/47f742ee-d925-43d2-b1e6-2693b000fca9/f3d11ce1-4533-4844-b6e6-a56584f46726
**_Issue3: Spinning icon is not as expected_**
![image](https://user-images.githubusercontent.com/60865903/82538642-ad532480-9b69-11ea-8e98-fe0c930541fd.png)

![image](https://user-images.githubusercontent.com/60865903/82538720-c9ef5c80-9b69-11ea-9174-35cb8b2a5894.png)

**_Issue4: Font size is different for project name_**
![image](https://user-images.githubusercontent.com/60865903/82539259-cdcfae80-9b6a-11ea-980e-356f2313597f.png)

![image](https://user-images.githubusercontent.com/60865903/82542344-72ec8600-9b6f-11ea-8ef6-925f711613e4.png)

**_Issue5: Backgroud color changes to white when height window is minimized in CLA Ready For Signature UI_**
![image](https://user-images.githubusercontent.com/60865903/82539927-de345900-9b6b-11ea-853d-a15534e67e53.png)

**Comment by amolsontakke3576** [comment]
@nirupamav Can you give me the steps to reproduce Issue 2 and Issue 5 ?

**Comment by nirupamav** [comment]
@amolsontakke3576 
Just minimize the window for e.g. reduce the window height
![image](https://user-images.githubusercontent.com/60865903/82548095-63256f80-9b78-11ea-8f95-dc9727123576.png)

**Comment by amolsontakke3576** [comment]
@nirupamav  For issue 4 font-size is different individual contributor screen and other screens. Most of the places it is 16px and only at individual contributor screen it is 14px so maybe it is designing issue and our header is common to all the screen, so we can set only one font size. (16px).

**Comment by nirupamav** [comment]
Verified and observed that the issues are fixed
**Issue1**  Now the color is rgb(224, 224, 224)
**Issue2**
![image](https://user-images.githubusercontent.com/60865903/84764889-09d02500-afec-11ea-851e-e44f09ec74c9.png)
**Issue3** Spinning icon is displayed as per wireframe
![image](https://user-images.githubusercontent.com/60865903/84764679-be1d7b80-afeb-11ea-8340-426a7921b21f.png)
**Issue4** Font size is 16px to be consistent across other pages as per the above comment by @amolsontakke3576 
**Issue5**
![image](https://user-images.githubusercontent.com/60865903/84765211-88c55d80-afec-11ea-83a7-d25bb5a4a82d.png)
