### ISSUE TITLE
(V2) Contributor Console - Corporate Flow - Issues in Enter Company Details popup

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla-contributor-console#17]
## Background
1. http://localhost:4200/corporate-dashboard/47f742ee-d925-43d2-b1e6-2693b000fca9/f3d11ce1-4533-4844-b6e6-a56584f46726
2. Enter Search criteria
3. Click on "+ Click Here"
4. Enter Company Details popup is opened
**_Issue1_**
5. Do not enter any data and Click Next
6. Observed no error message displayed and also no action is performed. Error message is displayed only when user moves the focus like click somewhere else or switch between windows
**Should the Next button be disabled until valid data is entered in the fields similar to the behavior of Proceed button in select company?**

**_Issue2_**
5. Observed that there is no full stop after Company. And the sentence **Leave unchecked if you do not want to create a full profile now.** should be displayed in next line and should be in italic
![image](https://user-images.githubusercontent.com/60865903/82632142-07f58a80-9c15-11ea-8e17-d584acfd4072.png)

**Comment by dealako** [comment]
Resolved - closing ticket.
