### ISSUE TITLE
(V2) Contributor Console - Corporate Flow - Company Already Exist dialog is different from wireframe

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla-contributor-console#18]
## Background
1. http://localhost:4200/corporate-dashboard/47f742ee-d925-43d2-b1e6-2693b000fca9/f3d11ce1-4533-4844-b6e6-a56584f46726
2. Enter Search criteria
3. Click on "+ Click Here"
4, Enter Company Details popup is opened
5. Enter valid data
6. Click Next
7. Company Already Exist dialog is displayed but is different from wireframe
Logo and button are different
**UI**
![image](https://user-images.githubusercontent.com/60865903/82634497-6faed400-9c1b-11ea-9b49-d3da59bdd2b4.png)

**Wireframe**
![image](https://user-images.githubusercontent.com/60865903/82634456-5c036d80-9c1b-11ea-917c-57cb41255704.png)

**Comment by dealako** [comment]
Resolved - closing ticket.
