### ISSUE TITLE
(V2) Contributor Console - Corporate Flow - Identify CLA Manager - Submit Request button is enabled when valid email address is not entered and no action performed when clicked 

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla-contributor-console#19]
## Background
1. http://localhost:4200/corporate-dashboard/47f742ee-d925-43d2-b1e6-2693b000fca9/f3d11ce1-4533-4844-b6e6-a56584f46726
2. Enter Search criteria
3. Click on "+ Click Here"
4. Enter Company Details popup is opened
5. Enter valid data
6. Click Next
7. Click Proceed
8. Click No
9. Do not enter any data and Click Submit
10. Observed that no action is performed and no error message is displayed
11. Enter invalid data for Email address
12. Click Submit
13. Observed that no action is performed and no error message is displayed
Error message is displayed only when user moves the focus like click somewhere else or switch between windows
Should the Submit Request button be disabled until valid email address is entered, similar to the behavior of Proceed button in select company?

**Comment by dealako** [comment]
Resolved - closing ticket.
