### ISSUE TITLE
(V2) Contributor Console - Corporate Flow - UI issues in Request Authorization to Contribute

### ISSUE THREAD

**Issue by nirupamav** [communitybridge/easycla-contributor-console#22]
## Background
1. http://localhost:4200/corporate-dashboard/47f742ee-d925-43d2-b1e6-2693b000fca9/f3d11ce1-4533-4844-b6e6-a56584f46726
2. Click Proceed
**_Issue_**
3. The text alignment of column headers and column values is left in wireframe but in UI it is center
Note: In wirframe for Action header the text-align is center. Not sure if this is as expected. Need to confirm with Pranab
![image](https://user-images.githubusercontent.com/60865903/82638417-7d1c8c00-9c24-11ea-8321-34aebbebcf82.png)

**_Issue2_**
4. Click Request Authorization
5. Observed Exit EasyCLA button is highlighted by default
![image](https://user-images.githubusercontent.com/60865903/82646559-6a10b880-9c32-11ea-984b-58a14b693fbf.png)

**Comment by amolsontakke3576** [comment]
@nirupamav For Issue 1 : In the wireframe for column headers and column values they used label, and we are using table view. As per look and feel text should be centred of the table. It's technical but you can check only look and feel.

**Comment by nirupamav** [comment]
Verified that Issue2 is fixed. Will check with Pranab regarding Issue2 and if required will log a ticket in EasyCLA board for the same. Closing the issue
