### ISSUE TITLE
EasyCLA Contributor Console - Help and FAQ Link Updates

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla-contributor-console#262]
## Summary

EasyCLA Contributor Console - Help and FAQ Link Updates

## Background

The help and FAQ links are invalid. This task is to update those links.  See page reference below.  Correct links should be similar to the EasyCLA landing page (reference below):

```html
<lfx-header product="LF CLA" id="lfx-header" userefreshtoken="true" [expanded]="hasExpanded" (toggled)="onToggled()" 
supportlink="https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/create/143" 
docslink="https://docs.linuxfoundation.org/lfx/easycla/v2-current"
faqlink="https://docs.linuxfoundation.org/lfx/easycla/v2-current/getting-started/easycla-faqs">
</lfx-header>
```

## Acceptance Criteria

1. Help and FAQ links are valid within the contributor console.

## References

1. [Help links](https://github.com/communitybridge/easycla-contributor-console/blob/main/src/index.html#L22)
2. [EasyCLA Landing Page Links](https://github.com/communitybridge/easycla/blob/main/cla-landing-page/src/app/app.component.html#L4-L8)

**Comment by thakurveerendras** [comment]
Now The help and FAQ links are as expected & mentioned above , So making issue status QA-Done

- Docs : https://docs.linuxfoundation.org/lfx/easycla/v2-current
- Support : https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/create/143
- FAQ : https://docs.linuxfoundation.org/lfx/easycla/v2-current/getting-started/easycla-faqs
