### ISSUE TITLE
Update EasyCLA Contributor Page Header

### ISSUE THREAD

**Issue by dealako** [communitybridge/easycla-contributor-console#297]
## Summary

Update EasyCLA Contributor Page Header

## Background

The design team has updated the standard header and footer for the LFX products.  This task is to update the EasyCLA contributor console page navigation/header.

## Tasks

- [ ] Update the EasyCLA contributor page to leverage the updated/new header and footer (with navigation)
- [ ] Tests and validate the updates

## Acceptance Criteria

- The new LFX header, footer, and navigation are integrated with the EasyCLA contributor page.

## References

**Comment by luismoriguerra** [comment]
code in review 
https://github.com/communitybridge/easycla-contributor-console/pull/296

also, we need to update the ssm params with the following values
cla-lfx-header-${stage}
Dev: https://cdn.dev.platform.linuxfoundation.org/lfx-header-v2.js
Prod: https://cdn.platform.linuxfoundation.org/lfx-header-v2.js

**Comment by dealako** [comment]
This change is deployed to production:

![Image](https://user-images.githubusercontent.com/519609/214949249-2bca93b1-f4e9-453a-bd85-65588e9d7a5f.png)
