### ISSUE TITLE
Resolve the vulnerabilities identified for "easycla-contributor-console"

### ISSUE THREAD

**Issue by mlehotskylf** [communitybridge/easycla-contributor-console#365]
Resolve the vulnerabilities identified for "easycla-contributor-console":

1. https://github.com/communitybridge/easycla-contributor-console/actions/runs/4786765076/jobs/8511110823?pr=360
2. https://github.com/communitybridge/easycla-contributor-console/actions/runs/4786765083/jobs/8511110767?pr=360

![Image](https://github.com/communitybridge/easycla-contributor-console/assets/49538656/7580bad2-9b6d-41cc-901b-26825564f070)

**Comment by dealako** [comment]
We may want to ask @amolsontakke3576 to assist.

**Comment by mlehotskylf** [comment]
All checks are passing for this repo now, here is latest PR: https://github.com/communitybridge/easycla-contributor-console/pull/424

Closing.
